### ISSUE TITLE
it does not work , the text is not there 

### ISSUE THREAD

**Issue by madadoux** [timbodeit/TextImageButton#1] opened 2020-04-10 13:29 UTC
I Have tried the example as you wrote but 
it does not work , the text is not there 
only the image

**Comment by timbodeit** [comment] 2020-04-10 23:20
Are you refering to the [Example project](https://github.com/timbodeit/TextImageButton/tree/master/Example) or the code in the Readme?

After updating the Swift Version and running a pod update, the example project seems to work fine when I run it with Xcode 11.4 on an iPhone 8 iOS 13.4 Simulator.

If the issue you're experiencing is not present with the example project, can you share a minimal example to reproduce the problem?

**Comment by madadoux** [comment] 2020-04-11 10:12
```
   button = TextImageButton()
        button.imagePosition = .right
        button.spacing = 20
        button.setTitle("I'm a TextImageButton", for: .normal)
        button.setImage(UIImage(named: "button_pause"), for: .normal)
        self.view.addSubview(button)
  button.snp.makeConstraints { (make) in
            make.height.equalTo(100)
            make.width.equalTo(200)
            make.top.equalTo(500)
        }
```
this is what I have done 
it appeared like image only

**Comment by madadoux** [comment] 2020-04-11 10:16
```
  button = TextImageButton(frame: CGRect(x: 30, y: 500, width: 200, height: 100))
        button.imagePosition = .right
        button.spacing = 20
        button.setTitle("I'm a TextImageButton", for: .normal)
        button.setImage(UIImage(named: "button_pause"), for: .normal)
        self.view.addSubview(button)
    
```
another code without snapkit same results

**Comment by timbodeit** [comment] 2020-04-11 10:35
Does your background have a different color than your button text?

**Comment by madadoux** [comment] 2020-04-11 10:57
yes black and white 
try this code on your own and tell me the result

**Comment by timbodeit** [comment] 2020-04-11 11:04
Looks good to me.

<img width="958" alt="Screenshot 2020-04-11 at 13 01 22" src="https://user-images.githubusercontent.com/4222754/79042053-aba25280-7bf4-11ea-9063-cbdd83a4fb9c.png">
<img width="988" alt="Screenshot 2020-04-11 at 13 00 28" src="https://user-images.githubusercontent.com/4222754/79042054-ad6c1600-7bf4-11ea-85b7-d09a56e8e549.png">

Please provide your example including the surrounding ViewController and background setup as a runnable Xcode workspace and include the Xcode and iOS Versions you are using so that I can reproduce your issue.

**Comment by timbodeit** [comment] 2020-05-01 15:50
Closing this issue due to lack of input. I would be happy to reopen it, if the issue still persists.

**Closed as completed by timbodeit** 2020-05-01 15:50 UTC
